//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Sample.Siege.Courier.WCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Siege.Courier.WCF.IWCFProtocol")]
    public interface IWCFProtocol {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFProtocol/Send", ReplyAction="http://tempuri.org/IWCFProtocol/SendResponse")]
        object Send(object message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFProtocolChannel : Web.Sample.Siege.Courier.WCF.IWCFProtocol, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFProtocolClient : System.ServiceModel.ClientBase<Web.Sample.Siege.Courier.WCF.IWCFProtocol>, Web.Sample.Siege.Courier.WCF.IWCFProtocol {
        
        public WCFProtocolClient() {
        }
        
        public WCFProtocolClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFProtocolClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFProtocolClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFProtocolClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object Send(object message) {
            return base.Channel.Send(message);
        }
    }
}
